<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\QuickDrop.Core\QuickDrop.Core.csproj" />
    <ProjectReference Include="..\..\src\QuickDrop.Network\QuickDrop.Network.csproj" />
  </ItemGroup>
</Project>
